version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: coop
      POSTGRES_PASSWORD: coop
      POSTGRES_DB: coopdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coop -d coopdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"

volumes:
  pgdata:
