name: docs-check
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --accept 200,206 'README.md' 'docs/**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


